version: '2.3'

services:
  citadel-bionic-dev:
    image: naokitakahashi12/ignition:citadel-bionic
    container_name: intel-citadel-bionic
    network_mode: "host"
    privileged: true
    group_add:
      - video
    environment:
      - MESA_GL_VERSION_OVERRIDE=4.2
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth/:/tmp/.docker.xauth:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - ign:/root/.ignition
    devices:
      - /dev/dri:/dev/dri
    working_dir: /usr/share/ignition/ignition-gazebo3/worlds
    command: /bin/sh -c "ign gazebo -v4 tunnel.sdf"

volumes:
  ign:
