version: '2.3'

services:
  citadel-bionic-dev:
    image: naokitakahashi12/ignition:citadel-bionic
    container_name: nvidia-citadel-bionic
    runtime: nvidia
    network_mode: "host"
    privileged: true
    group_add:
      - video
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - MESA_GL_VERSION_OVERRIDE=4.2
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - ign:/root/.ignition
    working_dir: /usr/share/ignition/ignition-gazebo3/worlds
    command: /bin/sh -c "ign gazebo -v4 tunnel.sdf"

volumes:
  ign:
